spring.application.name=KronoHertz
server.port=8088
# CONEXIÓN A MYSQL WORKBENCH
spring.datasource.url=jdbc:mysql://localhost:3306/kronohertz?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# Credenciales de acceso a MySQL
spring.datasource.username=root
spring.datasource.password=pa$$w0rd

# CONFIGURACIÓN DE HIBERNATE / JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# CONFIGURACIÓN DE THYMELEAF
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false